---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
   - name: stop nginx
     service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
   - name: stop apache
     service: name=apache2 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
   - name: restart mysql
     service: name=mysql state=restarted

# Bring stack up
- hosts: webserver
  become: true
  tasks:
   - name: start apache
     service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
   - name: start nginx
     service: name=nginx state=started
